swagger: '2.0'
info:
  description: 'This is the swagger about the online movie booking system '
  version: 1.0.0
  title: Swagger online movie booking system
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: petstore.swagger.io
basePath: /v2
tags:
  - name: movie
    description: Movie information
paths:
  /movie:
    post:
      tags:
        - movie
      summary: Add a new movie to the store
      description: ''
      operationId: addMovie
      parameters:
        - in: body
          name: body
          description: Movie that needs to be added to the list
          required: true
          schema:
            $ref: '#/definitions/Movie'
      responses:
        '405':
          description: Invalid input
  '/movie/{movieId}':
    put:
      tags:
        - movie
      summary: Update an existing movie
      description: ''
      operationId: updateMovie
      parameters:
        - in: body
          name: body
          description: Movie details need to be added
          required: true
          schema:
            $ref: '#/definitions/Movie'
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: Movie not found
        '405':
          description: Validation exception
  '/movie/{movieName}':
    get:
      tags:
        - movie
      summary: Find movie by name
      description: Returns a single movie
      operationId: getMovieById
      parameters:
        - name: moviename
          in: path
          description: movie name
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Movie'
        '400':
          description: Invalid ID supplied
        '404':
          description: Movie not found
    delete:
      tags:
        - movie
      summary: Deletes a movie
      description: ''
      operationId: deleteMovie
      parameters:
        - name: moviename
          in: path
          description: Movie name to delete
          required: true
          type: string
      responses:
        '400':
          description: Invalid Movie Name
        '404':
          description: Movie not found
      
definitions:
  
  Movie:
    type: object
    required:
      - name
      - photoUrls
    properties:
      movieName:
        type: string
      genre:
        type: string
        example: entertainment
      movieId:
        type: integer
        format: int64
      rating:
        type: integer
        format: int32
      releaseDate:
        type: string
        format: date
    xml:
      name: Movie
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
